on:
  workflow_dispatch:
  schedule:
    - cron: '47 5 * * *'
  push:

concurrency:
    group: main
    cancel-in-progress: true

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1

      - uses: actions/cache@v4
        with:
          path: /home/runner/.cache/deno/
          key: deno-deps

      - run: deno run --allow-net --allow-read --allow-write ./scripts/main.ts

      - run: find ./static -size +25M | tee /dev/stderr | xargs rm -f
        # remove too big files

      - run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Data"
            git push
          fi
